---
tap_install:
  values: 
    shared:
      ingress_domain: "tap.marygabry.name"
      # ingress_issuer: # Optional, can denote a cert-manager.io/v1/ClusterIssuer of your choice. Defaults to "tap-ingress-selfsigned".

      kubernetes_version: "1.25.5" # Required regardless of distribution when Kubernetes version is 1.25 or later.


    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    #The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

    #Below are the keys which may have default values set, but can be overridden.

    profile: full # Can take iterate, build, run, view.

    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:      
      registry:
        server: "gcr.io"
        repository: "pa-mbrodi/tap" 
      gitops:
        ssh_secret: ""
        branch: test
      git_implementation: libgit2 #! 2
      cluster_builder: default
      service_account: default

    scanning:
      metadataStore:
        url: ""

    # ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
    #   registry:
    #     server: "gcr.io" # Takes the value frxom the shared section by default, but can be overridden by setting a different value.
    #     repository: "pa-mbrodi/tap" # Takes the value from the shared section by default, but can be overridden by setting a different value.
    #   gitops:
    #   ssh_secret: "" # Takes "" as value by default; but can be overridden by setting a different value.


    contour:
      envoy:
        service:
          type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

    # buildservice:
    #   # Takes the value from the shared section by default, but can be overridden by setting a different value.
    #   kp_default_repository: "KP-DEFAULT-REPO"
    #   kp_default_repository_secret: # Takes the value from the shared section above by default, but can be overridden by setting a different value.
    #     name: "KP-DEFAULT-REPO-SECRET"
    #     namespace: "KP-DEFAULT-REPO-SECRET-NAMESPACE"

    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true # Creates a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Application Platform GUI and SCST - Store.
      app_config:
        auth:
          allowGuestAccess: true
        catalog:
          locations:
            - type: url
              target: https://github.com/mgbrodi/acme-catalog/blob/main/catalog-info.yaml
              
    metadata_store:
      ns_for_export_app_cert: "*" # Verify this namespace is available within your cluster before initiating the Tanzu Application Platform installation.
      app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

    grype:
      namespace: "tap-install" # Verify this namespace is available within your cluster before initiating the Tanzu Application Platform installation.
      targetImagePullSecret: "tap-registry"
      # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.

    policy:
      tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.

    cnrs:
      domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/1.5.2
        subPath: clusters/tap-on-azure/cluster-config/namespaces
        url: https://github.com/mgbrodi/tap-gitops
      additional_sources:
      - git:
          ref: origin/1.5.2
          subPath: clusters/tap-on-azure/cluster-config/namespaces/namespace-resources
          url: https://github.com/mgbrodi/tap-gitops
        path: _ytt_lib/namespace-resources
    #  - git:
    #       ref: origin/main
    #       subPath: ns-provisioner-samples/testing-scanning-supplychain-polyglot
    #       url: https://github.com/vmware-tanzu/application-accelerator-samples.git
    #     path: _ytt_lib/testing-scanning-supplychain-polyglot-setup
