apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: all-apps
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
spec:
  serviceAccountName: sync-sa
  fetch:
    - git:
        ref: origin/1.5.2
        url: https://github.com/mgbrodi/tap-gitops
        subPath: clusters/tap-on-azure/cluster-config/apps
  template:
    - ytt: {}
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]