apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  finalizers:
  - resourceclaims.services.apps.tanzu.vmware.com/finalizer
  - resourceclaims.services.apps.tanzu.vmware.com/lease-finalizer
  name: external-azure-db-claim
  namespace: default
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: external-azure-db-binding-compatible

